In [1]:
from __future__ import print_function 
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[ 7.8534e+34,  4.7418e+30,  5.9663e-02],
        [ 7.0374e+22,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-2.5244e-29,  0.0000e+00, -2.5244e-29],
        [ 8.4078e-45, -2.5244e-29,  0.0000e+00]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.5273, 0.6498, 0.9222],
        [0.4588, 0.7536, 0.6078],
        [0.5766, 0.3910, 0.8367],
        [0.2956, 0.3928, 0.6831],
        [0.6896, 0.8225, 0.7236]])


In [4]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
print(x.size())

torch.Size([2])


In [7]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.3996, -1.5289,  1.1823],
        [-0.7801,  0.5093, -0.4376],
        [-0.7581,  0.6790,  0.0860],
        [-0.9950, -1.2304, -0.3832],
        [-0.6563,  0.1108,  0.0554]])


In [9]:
y = torch.rand(5,3)
print(x+y)
print(torch.add(x,y))

tensor([[ 2.2967, -1.3040,  1.4141],
        [-0.6111,  1.3901,  0.3337],
        [-0.4631,  0.9565,  0.7952],
        [-0.5168, -0.7097,  0.0824],
        [-0.2072,  0.5878,  1.0225]])
tensor([[ 2.2967, -1.3040,  1.4141],
        [-0.6111,  1.3901,  0.3337],
        [-0.4631,  0.9565,  0.7952],
        [-0.5168, -0.7097,  0.0824],
        [-0.2072,  0.5878,  1.0225]])


In [10]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 2.2967, -1.3040,  1.4141],
        [-0.6111,  1.3901,  0.3337],
        [-0.4631,  0.9565,  0.7952],
        [-0.5168, -0.7097,  0.0824],
        [-0.2072,  0.5878,  1.0225]])


In [11]:
y.add_(x)
print(y)

tensor([[ 2.2967, -1.3040,  1.4141],
        [-0.6111,  1.3901,  0.3337],
        [-0.4631,  0.9565,  0.7952],
        [-0.5168, -0.7097,  0.0824],
        [-0.2072,  0.5878,  1.0225]])


In [12]:
print(x[:, 1])

tensor([-1.5289,  0.5093,  0.6790, -1.2304,  0.1108])


In [13]:
if torch.cuda.is_available(): 
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y 
    print(z)
    print(z.to("cpu", torch.double))

In [14]:
torch.cuda.is_available()

False

In [15]:
x = torch.ones(2,2,requires_grad = True)

In [19]:
y = x +2 
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [17]:
print(y.grad_fn)

In [22]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [23]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [26]:
x = torch.randn(3, requires_grad = True)
y = x * 2
while y.data.norm() < 1000: 
    y = y*2
    
print(y)

tensor([-688.3414, -693.4837, -223.7990], grad_fn=<MulBackward0>)


In [27]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
